steps:
  - label: "[CUDA] Julia v1.10"
    plugins:
      - JuliaCI/julia#v1:
          version: "1.10"
      - JuliaCI/julia-test#v1: ~
      - JuliaCI/julia-coverage#v1:
          codecov: false # TODO
    agents:
      queue: "juliagpu"
      cuda: "*"
    if: build.message !~ /\[skip tests\]/
    timeout_in_minutes: 20
    env:
      CI_USE_CUDA: "1"

  - label: "[ROCm] Julia v1.10"
    plugins:
      - JuliaCI/julia#v1:
          version: "1.10"
      - JuliaCI/julia-test#v1: ~
      - JuliaCI/julia-coverage#v1:
          codecov: false # TODO
    agents:
      queue: "juliagpu"
      rocm: "*"
    if: build.message !~ /\[skip tests\]/
    timeout_in_minutes: 20
    env:
      CI_USE_ROCM: "1"

  - label: "[Metal] Julia v1.10"
    plugins:
      - JuliaCI/julia#v1:
          version: "1.10"
      - JuliaCI/julia-test#v1: ~
      - JuliaCI/julia-coverage#v1:
          codecov: false # TODO
    agents:
      queue: "juliaecosystem"
      os: "macos"
      arch: "aarch64"
    if: build.message !~ /\[skip tests\]/
    timeout_in_minutes: 20
    env:
      CI_USE_METAL: "1"
